FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["DynamicConfigLib.Core/DynamicConfigLib.Core.csproj", "DynamicConfigLib.Core/"]
COPY ["DynamicConfigLib.Api/DynamicConfigLib.Api.csproj", "DynamicConfigLib.Api/"]
RUN dotnet restore "DynamicConfigLib.Api/DynamicConfigLib.Api.csproj"

COPY . .
WORKDIR "/src/DynamicConfigLib.Api"
RUN dotnet build "DynamicConfigLib.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DynamicConfigLib.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DynamicConfigLib.Api.dll"] 